# Generated by Django 3.1.7 on 2021-07-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etablissement',
            old_name='nom_formation',
            new_name='nom_etablissement',
        ),
        migrations.RemoveField(
            model_name='etablissement',
            name='type_partenaire',
        ),
        migrations.AddField(
            model_name='employer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='partenaire_financier',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='partenaire_technique',
            field=models.BooleanField(blank=True, default=0),
        ),
    ]
