# Generated by Django 3.1.7 on 2021-07-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210718_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etablissement',
            old_name='last_materiel',
            new_name='liste_materiel',
        ),
        migrations.RenameField(
            model_name='etablissement',
            old_name='superfice_agricole',
            new_name='superficie_agricole',
        ),
    ]
