# Generated by Django 3.1.7 on 2021-08-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
