# Generated by Django 3.1.7 on 2021-08-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210812_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='auto_emploie_femme',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='auto_emploie_homme',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='emploie_partenaire',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
