# Generated by Django 3.1.7 on 2021-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210812_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='autre_apreciation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
