# Generated by Django 3.1.7 on 2021-08-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210812_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='liste_materiel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
