# Generated by Django 3.1.7 on 2021-08-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210812_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='nb_forme',
            new_name='nb_homme',
        ),
    ]
