# Generated by Django 3.1.7 on 2021-08-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210820_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etablissement',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='etablissement',
            old_name='longittude',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='formation',
            name='c_autre_nom',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Formation_modulaire',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom_formation', models.CharField(blank=True, max_length=500, null=True)),
                ('niveau_requis', models.CharField(blank=True, max_length=500, null=True)),
                ('c_concours', models.BooleanField(blank=True, default=0, null=True)),
                ('c_dossier', models.BooleanField(blank=True, default=0, null=True)),
                ('c_autre', models.BooleanField(blank=True, default=0, null=True)),
                ('c_autre_nom', models.CharField(blank=True, max_length=500, null=True)),
                ('c_entretien', models.BooleanField(blank=True, default=0, null=True)),
                ('duree', models.CharField(blank=True, max_length=500, null=True)),
                ('nb_homme', models.IntegerField(blank=True, default=0, null=True)),
                ('nb_femme', models.IntegerField(blank=True, default=0, null=True)),
                ('attestation', models.CharField(blank=True, max_length=500, null=True)),
                ('metier', models.CharField(blank=True, max_length=500, null=True)),
                ('accreditation', models.CharField(blank=True, max_length=500, null=True)),
                ('date_accreditation', models.CharField(blank=True, max_length=500, null=True)),
                ('structure_accreditation', models.CharField(blank=True, max_length=500, null=True)),
                ('habilitation', models.CharField(blank=True, max_length=500, null=True)),
                ('date_habilitation', models.CharField(blank=True, max_length=500, null=True)),
                ('structure_habilitation', models.CharField(blank=True, max_length=500, null=True)),
                ('cout_formation', models.CharField(blank=True, max_length=500, null=True)),
                ('nb_sortant_homme', models.IntegerField(blank=True, default=0, null=True)),
                ('nb_sortant_femme', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.etablissement')),
            ],
        ),
    ]
