# Generated by Django 3.1.7 on 2021-10-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210831_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='autre_apreciation',
            field=models.TextField(blank=True, null=True, verbose_name='autre apréciation'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='crée le'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='date_de_creation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ministére de pêche'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='dc_email',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='email représentant'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='dc_genre',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='genre représentant'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='dc_nom',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='nom représentant'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='dc_telephone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='téléphone représentant'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='existance_bd',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='existance base de données'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='m_agriculture',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='ministére agriculture'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='m_autre',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='ministére autre'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='m_elevage',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='ministére élevage'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='m_enseignant_sup',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='ministére enseignement superieur'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='m_femme',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='ministére jeunesse'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='m_formation',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='ministére formation professionnelle'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='m_jeunesse',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='ministére femme'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='m_peche',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='ministére de pêche'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='m_si_autre',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='nom autre ministére'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='nom_etablissement',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="nom de l'établissement"),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='region',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='région'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='site_web',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='telephone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ministére de pêche'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='mise à jour'),
        ),
    ]
