# Generated by Django 3.1.7 on 2021-10-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211021_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='crée le'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='mise à jour'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='auto_domaine',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='autre domaine'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='crée le'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='mise à jour'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='telephone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ministére  pêche'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='c_autre',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='accès autre'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='c_autre_nom',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='nom autre accès'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='c_concours',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='accès concours'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='c_dossier',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='accès dossier'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='c_entretien',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='accès entretien'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='cout_formation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='coût formation'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='crée le'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_attestation',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='diplôme ATTESTATION'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_autre',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='autre diplôme'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_autre_nom',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='diplôme autre nom'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_bac',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='diplôme BAC'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_bt',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='diplôme BT'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_bts',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='diplôme BTS'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_cap',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='diplôme CAP'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_certificat',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='diplôme CERTIFICAT'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_cs',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='diplôme CS'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_doctorat',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='diplôme DOCTORAT'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_dts',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='diplôme DTS'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_licence',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='diplôme LICENCE'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='d_master',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='diplôme MASTER'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='mise à jour'),
        ),
        migrations.AlterField(
            model_name='formation_modulaire',
            name='c_autre',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='accès autre'),
        ),
        migrations.AlterField(
            model_name='formation_modulaire',
            name='c_autre_nom',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='nom autre accès'),
        ),
        migrations.AlterField(
            model_name='formation_modulaire',
            name='c_concours',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='accès concours'),
        ),
        migrations.AlterField(
            model_name='formation_modulaire',
            name='c_dossier',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='accès dossier'),
        ),
        migrations.AlterField(
            model_name='formation_modulaire',
            name='c_entretien',
            field=models.BooleanField(blank=True, default=0, null=True, verbose_name='accès entretien'),
        ),
        migrations.AlterField(
            model_name='formation_modulaire',
            name='cout_formation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='coût formation'),
        ),
        migrations.AlterField(
            model_name='formation_modulaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='crée le'),
        ),
        migrations.AlterField(
            model_name='formation_modulaire',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='mise à jour'),
        ),
    ]
