# Generated by Django 3.1.7 on 2021-10-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211021_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='date_de_creation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='site_web',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='telephone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='téléphone'),
        ),
    ]
