# Generated by Django 3.1.7 on 2021-12-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='message',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
