# Generated by Django 3.1.7 on 2021-12-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211216_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='nom_ref',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
